### ISSUE TITLE
Missing Goals

### ISSUE THREAD

**Issue by makopov** [uberFoo/dwarf#1]
Since discovering this newly launched language, I've been thrilled with its potential and its unique features. 
Unfortunately, one important detail that seems to be missing from the README file is the set of goals for the language. 
Could the developers perhaps add a section that outlines these goals, as this would provide potential contributors and users with a clearer understanding of the project's direction and intentions? 
Knowledge of these objectives would be particularly beneficial for those considering contributing to the project.

In order to facilitate this, perhaps a brief discussion among the core team could help define these goals. 
This way, everyone involved in the project would have a comprehensive understanding of the overall vision and where they can contribute most effectively. Thanks for considering this suggestion!

**Comment by uberFoo** [comment]
Thank you Misha.
